inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
