Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
